In [1]:
import numpy as np
import pandas as pd
import scipy
import matplotlib as plt
import seaborn as sns
import sklearn

In [2]:
df = pd.read_csv('example.csv')
df

one       two     three
0   example1  example2  example3
1         T1        T2        T3
2     Sunday    Monday   Tuesday
3  Wednesday  Thursday    Friday
4   Saturday       NaN       NaN
5      One 1     Two 2   Three 3

In [3]:
import csv

In [4]:
with open('example.csv', 'rt') as f:
    data= csv.reader(f)
    for i in data:
        print(i)

['one', 'two', 'three']
['example1', 'example2', 'example3']
['T1', 'T2', 'T3']
['Sunday', 'Monday', 'Tuesday']
['Wednesday', 'Thursday', 'Friday']
['Saturday', '', '']
['One 1', 'Two 2', 'Three 3']


In [5]:
reader=csv.DictReader(open('example.csv', 'rt'))
for i in reader:
    print(i)

{'one': 'example1', 'two': 'example2', 'three': 'example3'}
{'one': 'T1', 'two': 'T2', 'three': 'T3'}
{'one': 'Sunday', 'two': 'Monday', 'three': 'Tuesday'}
{'one': 'Wednesday', 'two': 'Thursday', 'three': 'Friday'}
{'one': 'Saturday', 'two': '', 'three': ''}
{'one': 'One 1', 'two': 'Two 2', 'three': 'Three 3'}


In [6]:
with open('example.csv', mode='a') as f:
    writer=csv.writer(f,delimiter=',',quotechar=",",quoting=csv.QUOTE_MINIMAL)
    writer.writerow(['One 1','Two 2','Three 3'])

In [7]:
ass1=np.arange(9)
ass1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
ass1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
ass2=np.arange(10)

In [10]:
for i in ass2:
    if ass2[i]%2 == 1:
        ass2[i] = -1
ass2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [11]:
x=np.array([21,64,86,22,74,55,81,79,90,89])
y=np.array([21,7,3,45,10,29,55,4,37,18])
a = []
b = []

In [12]:
for i in range(10):
    if x[i] > y[i]:
        a.append(i)
    if x[i] == y[i]:
        b.append(i)

In [13]:
a

[1, 2, 4, 5, 6, 7, 8, 9]

In [14]:
b

[0]

In [15]:
ass4 = np.arange(100).reshape(5,-1)

In [16]:
ass4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [17]:
ass4[0:, 0:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [18]:
adq1 = []
for i in range(10):
    adq1.append(np.random.randint(30,40))
adq1

[39, 33, 39, 39, 36, 30, 39, 38, 31, 35]

In [19]:
matA=np.arange(9).reshape(3,3)
matA

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
matA + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
matA[-1][-1] + 1

9

In [22]:
matA

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
matA += 1

In [24]:
matA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
matA[-1][-1] += 1

In [26]:
matA

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [27]:
matA[2]

array([ 7,  8, 10])

In [28]:
matB = np.array([7,8,10,4,5,6,1,2,3]).reshape(3,3)

In [29]:
matB

array([[ 7,  8, 10],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [30]:
matC = matA + matB

In [31]:
matC

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [32]:
matE = matA - matB

In [33]:
matE

array([[-6, -6, -7],
       [ 0,  0,  0],
       [ 6,  6,  7]])

In [34]:
matD = matA.dot(matB)
matD

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

In [35]:
matE.transpose()

array([[-6,  0,  6],
       [-6,  0,  6],
       [-7,  0,  7]])